### ISSUE TITLE
Support Case Sensitive Regex in KeywordService.cs

### ISSUE THREAD

**Issue by bauzer714** [vaindil/wazebot-discord#13]
Title mostly says it all.  The current regex doesn't allow the case insensitive to be overridden. The default of case insensitive would be a mess to change for people, and could support just do the inverted of /regex/s.

Test case:  currently /UP/ will alert for up or UP. 
New Test Case.  /UP/s will alert for UP, but not up.     /s is merely a suggestion - I don't care what you go with.

**Comment by vaindil** [comment]
This is under review in #14.
