### ISSUE TITLE
Keyword additional atribute

### ISSUE THREAD

**Issue by jdelosa** [vaindil/wazebot-discord#3]
Hi, first i want to sat thanks for all your work.
i was wondering if you can add a additional attribute to the Keyword function so that when you add a new keyword you can just add it to a channel or a server or globally. like you have for Ignore.
this way you can add a keyword like Downlock to just the channels you have edit area rather that having to go ignore all the channels you don't 
If you have any thoughts please let me know.
I know this would be low on the list but i think it would be worth wild
Thanks Again John (JD Brooklyn NY USA)

**Comment by vaindil** [comment]
Yeah, this was requested by someone in the national server, I just didn't open an issue here, probably should've. I need to figure out the syntax for the command, but it should be doable.

**Comment by jdelosa** [comment]
It might have been me.... I did post it there and PZ recommend me making it
into a formal request.
Thanks John.....

Also if at anytime you need a guinea pig to test something I am always
willing to help.

**Comment by vaindil** [comment]
This repo is no longer in use, so the issue is being closed. The new repo is [here](https://gitlab.com/SixbucksSolutions/CommunityBot).

**Comment by jdelosa** [comment]
First of all, thank you for all you work with the Bot.... It has been a
great help.
If possible can you forward me the orginal request I made about the ignore.
I would appreciate it.
Thanks JD
