### ISSUE TITLE
Twitter feed which supports regex include and exclude filtering

### ISSUE THREAD

**Issue by PesachZ** [vaindil/wazebot-discord#5]
Ability to subscribe to this feeds or Twitter by search (multiple feeds) and then implement keyword, phrase, or regex filters to include or exclude as additional filters on the feed.

**Comment by vaindil** [comment]
This repo is no longer in use, so the issue is being closed. The new repo is [here](https://gitlab.com/SixbucksSolutions/CommunityBot).
