### ISSUE TITLE
Set up sync to/from GHO for NOR and NER

### ISSUE THREAD

**Issue by PesachZ** [vaindil/wazebot-discord#7]
Please link these two GHOs to their respective channels with 2way sync. One per region. For those who don't have access to NOR > gho_compatibility Channel ID: 355055029717172236
Server ID: 300481818619150336
GHO: Waze NOR Discord Sync

**Comment by PesachZ** [comment]
Typo there:
Please link these two GHOs to their respective channels with 2way sync. One per region. For those who don't have access to Discord.

NOR > gho_compatibility Channel ID: 355055029717172236
Server ID: 300481818619150336
GHO: Waze NOR Discord Sync

NER > gho_compatibility Channel ID: 355055097585336321
Server ID: 300482201198395417
GHO: Waze NER Discord Sync

**Comment by vaindil** [comment]
The GHO sync bot needs to be added to each of the servers by an admin using [this link](https://discordapp.com/api/oauth2/authorize?client_id=333960669839884290&scope=bot&permissions=0), then I can set up the sync.

**Comment by PesachZ** [comment]
Done, bot is in both NER and NOR. Thank you

**Comment by vaindil** [comment]
This repo is no longer in use, so the issue is being closed. The new repo is [here](https://gitlab.com/SixbucksSolutions/CommunityBot).
