### ISSUE TITLE
Announce autoreplies changes in dedicated channel per server

### ISSUE THREAD

**Issue by PesachZ** [vaindil/wazebot-discord#9]
As I understand it this is an enhancement request which applies globally. Announce any change to autoreplies on the server where they are submitted. It could be in a designated #bot channel that only the bot (and admins by default) have access to. There could be a check built in to see if the channel exists first, and if there's no channel to not try and post the message so there isn't an error issue. If a server removed the channel they would lose the function until they restored the channel. It would be safeguard security system for bot integrity, and a way to identify if there is foul play. This would also create a defacto changelog.

**Comment by vaindil** [comment]
This repo is no longer in use, so the issue is being closed. The new repo is [here](https://gitlab.com/SixbucksSolutions/CommunityBot).
